version: '3'
services:
  asset-fe:
    build: .
    ports: 
      - 8080:8080
  asset-db:
    image: postgres:12-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
